Error: params: ParamMap on character-list.component.ts
TS7052: Element implicitly has an 'any' type because type 'ParamMap' has no index signature. Did you mean to call 'params.get'?